contact_links:
    - name: 🤔 Questions and Help
      url: https://t.me/PythonAmazonPAAPI
      about: This issue tracker is not for support questions. Please refer to our Telegram group for help or use the discussions section.
